@echo off
REM ============================================================================
REM Step 3: Clear Old Incorrect Signals from Database
REM Removes the 200 ALL-BUY signals with clustered confidence scores
REM ============================================================================

cd ..\backend\turbomode

echo.
echo ============================================================================
echo STEP 3: CLEAR BAD SIGNALS
echo ============================================================================
echo.
echo This will delete the 200 incorrect signals from turbomode.db
echo (All were BUY with 99%% confidence - generated by broken model)
echo.
echo WARNING: This cannot be undone!
echo.
pause

..\..\venv\Scripts\python.exe -c "from database_schema import TurboModeDB; db = TurboModeDB(); db.clear_all_data(); print('[OK] Cleared all old signals from turbomode.db')"

echo.
echo ============================================================================
echo BAD SIGNALS CLEARED
echo ============================================================================
echo.
echo Next step: Run 4_test_scan.bat
echo.
pause
